### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jagardaniel** [jagardaniel/transit-memory-game#1]
## Some things to do

- [ ] SVG icons loads in full size before resizing to their intended size. Makes it look glitchy on page load.
- [ ] Re color SVG icons from Wikipedia for metro and rail used in "Start new game".
- [ ] Add statistics about current completed guesses for each line and in total.
- [ ] Add a list of all completed guesses. Clicking the station name should zoom to the station on the map.
- [ ] Select all/clear button for line selections when starting a new game.
- [ ] Zoom level when guessing a correct station should depend on the initial size of the bounding box. Correct guesses for Pendeltåg stations should zoom in less than for Spårväg City for example.
- [ ] Add menu with options to restart the game and copy the current stats (guesses for each line etc).
